[project]
name = 'zoriel_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.funding]
path = 'contracts/funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.ress]
path = 'contracts/ress.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_quota]
path = 'contracts/storage_quota.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identity]
path = 'contracts/user_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.versioned_storage]
path = 'contracts/versioned_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_change_allowed]
path = 'contracts/vote_change_allowed.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_with_allowed_change]
path = 'contracts/vote_with_allowed_change.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
